spring:
  application:
    name: pedido
  datasource:
    username: toddy
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: toddy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8081
