spring:
  application:
    name: pedido
  datasource:
    username: toddy
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: toddy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 8081
